---
AllCops:
  Exclude:
    - 'vendor/**/*'
Metrics/BlockLength:
  Enabled: false
# Metrics/ClassLength:
#   Enabled: false
# Metrics/LineLength:
#   Enabled: false
# Metrics/MethodLength:
#   Enabled: false
# Style/FormatStringToken:
#   Enabled: false
